### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by txAnnie** [rbawden/discourse-mt-test-sets#1]
Please tell the detail of how to use your test sets to evaluate the MT model, thanks.

**Comment by rbawden** [comment]
Hi!  The test set should be used  to evaluate contextual MT models (that use the previous sentence when making translating the current sentence). In the files, for each example input sentence, the previous sentence (and its translation) is given, as well as two different translations of the current sentence: one correct (marked “correct” or “semi-correct”) and one incorrect (marked “incorrect”).

Neural machine translation systems can be used to produce a score/cost (e.g. cross entropy) for an existing translation of a sentence and we take advantage of this here. For each possible target sentence (correct and incorrect) you pass it, its source sentence and the previous sentence through the machine translation system to get a score. You should then compare the score between the one obtained when inputting the correct translation and the one obtained for the incorrect translation. If the score is better (cross entropy = lower) for the correct translation than for the incorrect translation, then we say that the example has been correctly scored by the system. The percentage of examples correctly scored is then calculated over the entire test set, to give the overall performance of the model.

The sentences are provided in their raw format here as it will depend on your contextual translation model how the sentences are to be given to the model. So you will have to extract the source sentences, previous sentences and target sentences from the .json files.

I hope this helps!

**Comment by rbawden** [comment]
I have just added some scripts to extract the sentences from the .json files and to evaluate the final scores. Their usage is documented in the readme. Let me know if you run into any problems!
